sudo: required
services:
  - docker
language: bash

before_script:
  # dependencies
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - sudo pip install j2cli requests
  - wget https://github.com/riotkit-org/ci-utils/archive/master.zip -O /tmp/ci-utils.zip  # change master to a release tag only here (version)
  - curl "https://raw.githubusercontent.com/riotkit-org/ci-utils/master/ci-integration/travis.sh" -s | bash

  # activate ARM builds on travis
  - /opt/riotkit/utils/bin/setup-travis-arm-builds
  - sudo apt-get install qemu-user-static
  - docker buildx create --name mybuilder
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap
script:
  # build image
  - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t noim/idrac6-hap .
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker tag noim/idrac6-hap noim/idrac6-hap:latest
      docker push noim/idrac6-hap:latest
      docker push noim/idrac6-hap
    fi
