sudo: required
services:
  - docker
language: bash

before_script:
  # dependencies
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - sudo pip install j2cli requests
  - sudo pip install rkt-armutils==3.0.3

  # activate ARM builds on travis
  - rkd :travis:configure-qemu
  - docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
  - sudo systemctl restart docker
  - docker buildx create --name mybuilder --platform linux/amd64,linux/arm64,linux/arm/v7
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap
script:
  # build & push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t noim/idrac6-hap:latest --push .
    else
      docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t noim/idrac6-hap:latest .
    fi
