services:
  - docker
env:
  global:
    - QEMU_VER=v2.9.1
  matrix:
    - ARCH=amd64
    - ARCH=armhf
    - ARCH=aarch64
language: bash
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t noim/idrac6-hap .
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker tag noim/idrac6-hap noim/idrac6-hap:latest
      docker push noim/idrac6-hap:latest
      docker push noim/idrac6-hap
    fi
